window.pagesData = [
  { page: 1, title: "Half Title", chapter: 0, searchText: "" },
  { page: 2, title: "Title Page — Frame Innovation", chapter: 0, searchText: "frame innovation" },
  { page: 3, title: "Series Page — Design Thinking, Design Theory", chapter: 0, searchText: "design thinking design theory Ken Friedman Erik Stolterman editors" },
  { page: 4, title: "Full Title — Create New Thinking by Design", chapter: 0, searchText: "frame innovation create new thinking by design Kees Dorst MIT Press" },
  { page: 5, title: "Copyright", chapter: 0, searchText: "2015 Massachusetts Institute of Technology all rights reserved" },
  { page: 6, title: "Contents (Part 1)", chapter: 0, searchText: "contents series foreword acknowledgments preface challenges pioneers lessons from design" },
  { page: 7, title: "Contents (Part 2)", chapter: 0, searchText: "principles practices frame creation open complex dynamic networked organization" },
  { page: 8, title: "Series Foreword — Design as a Young Profession", chapter: 0, searchText: "series foreword professions design relatively young practice predates making things useful goal tools" },
  { page: 9, title: "Series Foreword — The Word 'Design'", chapter: 0, searchText: "draw plans create fashion execute construct according to plan noun" },
  { page: 10, title: "Series Foreword — Common Attributes of Design", chapter: 0, searchText: "act on physical world address human needs generate built environment common attributes" },
  { page: 11, title: "Series Foreword — Analytic and Synthetic Skills", chapter: 0, searchText: "experience development necessary no longer sufficient analytic synthetic planning skills" },
  { page: 12, title: "Series Foreword — Profound Knowledge", chapter: 0, searchText: "solid theory W Edwards Deming profound knowledge physicist engineer designer" },
  { page: 13, title: "Blank", chapter: 0, searchText: "" },
  { page: 14, title: "Acknowledgments", chapter: 0, searchText: "acknowledgments culmination many years design practice design research collaboration friends colleagues" },
  { page: 15, title: "Acknowledgments (continued)", chapter: 0, searchText: "Phyllis Crabill English Claudy te Brake figures MIT Press editorial team" },
  { page: 16, title: "Preface — Living in Unusual Times", chapter: 0, searchText: "preface living unusual times challenged navigate increasingly complex dynamic world individuals professional" },
  { page: 17, title: "Preface — A Do-It-Yourself Guide", chapter: 0, searchText: "methods do-it-yourself guide deep understanding principles practices frame creation practitioner develop approach" },
  { page: 18, title: "Chapter 1: Challenges — We Are Not Solving Our Problems Anymore", chapter: 1, searchText: "challenges we are not solving our problems anymore news natural disasters endless succession" },
  { page: 19, title: "Alternative Ways to Tackle Complex Problems", chapter: 1, searchText: "alternative ways tackle open complex dynamic networked problems leading innovators design" },
  { page: 20, title: "Extending Our Problem-Solving Repertoire", chapter: 1, searchText: "extend repertoire problem-solving practices complex networked world created not a moment to lose" },
  { page: 21, title: "Stakeholders and Institutional Complexity", chapter: 1, searchText: "coming of age number stakeholders skyrocketed institutional railway company airport" },
  { page: 22, title: "The High-Speed Train Route Decision", chapter: 1, searchText: "planning office route chosen major tunnel minimize impact sensitive environmental area old-fashioned" },
  { page: 23, title: "A Huge Shift for Industrial-Age Organizations", chapter: 1, searchText: "huge shift organizations grown thrived industrial age dealing change advances technology" },
  { page: 24, title: "Redefining Quality — Bang & Olufsen Case", chapter: 1, searchText: "Verganti case study redefinition quality away from complete new approach Bang Olufsen" },
  { page: 25, title: "High Ideals Without Understanding Everyday Life", chapter: 1, searchText: "carriers high ideals not built deep understanding everyday life people planning to change" },
  { page: 26, title: "Social Housing and Stuck Communities", chapter: 1, searchText: "basically stuck polite society looks away does not want to go there social housing" },
  { page: 27, title: "The Nature of Complex Problems", chapter: 1, searchText: "assumptions factor stakeholder excluded haunt problem-solving process problem context merge complex" },
  { page: 28, title: "Open, Complex, Dynamic, and Networked Problems", chapter: 1, searchText: "open no boundaries complex many elements relationships dynamic change over time networked across organizations" },
  { page: 29, title: "Problems vs. Conventional Methods", chapter: 1, searchText: "open complex dynamic networked problems do not gel conventional problem-solving methods strategies" },
  { page: 30, title: "Harder Problem Boundaries", chapter: 1, searchText: "150 years should know how to do this problem boundaries harder to draw complex dynamic context" },
  { page: 31, title: "Five Syndromes of Conventional Organizations", chapter: 1, searchText: "lone warrior freeze the world self-made box rational high ground identification five syndromes" },
  { page: 32, title: "Heroic Problem-Solving and Frustration", chapter: 1, searchText: "lead party heroically shouldered too much problem-solving responsibility one step from deep frustration" },
  { page: 33, title: "Holding On to Conventional Practices", chapter: 1, searchText: "worst-case scenario organization holding conventional practices dear life defeatism not knowing why" },
  { page: 34, title: "Unquestioning Belief in Rationality", chapter: 1, searchText: "strange correlation unquestioning belief rationality utter madness continuing apply situations clearly" },
  { page: 35, title: "Moving Forward — Complexity Without Direction Paralyzes", chapter: 1, searchText: "moving forward Boutellier complexity without direction paralyzes powerlessness five underlying" },
  { page: 36, title: "Twisted Rationality and Sealed Logic", chapter: 1, searchText: "limited twisted rationality chilling reader realizes logic completely sealed within identity society" },
  { page: 37, title: "First-Generation Immigrants and Integration", chapter: 1, searchText: "first-generation immigrants stayed kids grown up new country second generation integration" },
  { page: 38, title: "Understanding Underlying Structures", chapter: 1, searchText: "crucial understand underlying structures specific situation exploring solutions emerge problem situation" },
  { page: 39, title: "Chapter 1 Transition", chapter: 1, searchText: "" },
  { page: 40, title: "Chapter 2: Pioneers — The Young Designers Foundation", chapter: 2, searchText: "pioneers Young Designers foundation explore design-based practices alternative conventional problem-solving innovation" },
  { page: 41, title: "Employment Services Company Case", chapter: 2, searchText: "companies supplied temporary staff client companies trouble cementing relationship temporary staff" },
  { page: 42, title: "Design Proposals to Spark Debate", chapter: 2, searchText: "design proposals spark debate employment services company sketch proposals Orgacom" },
  { page: 43, title: "Integrated Living of Mentally Handicapped People", chapter: 2, searchText: "mentally handicapped persons live life normally possible rehousing independently reversed conventional wisdom" },
  { page: 44, title: "Difficulties in Research with Handicapped People", chapter: 2, searchText: "problems group mildly handicapped difficulties verbal expression social interaction often illiterate" },
  { page: 45, title: "YD Project Book — Care and Control", chapter: 2, searchText: "YD project book Suyling Krabbendam Dorst major theme strange relationship care control" },
  { page: 46, title: "Street Fashion and Identity", chapter: 2, searchText: "street fashion identity growing up in public Young Designers foundation project-based approach environments" },
  { page: 47, title: "Fashion Studio and Positive Identity", chapter: 2, searchText: "YD publication fashion project generation pride creation positive identity fashion studio concept" },
  { page: 48, title: "Designing Against Crime Centre", chapter: 2, searchText: "University Technology Sydney Designing Against Crime Centre London Thorpe Gamman remit use" },
  { page: 49, title: "Kings Cross at Night", chapter: 2, searchText: "Kings Cross night law-and-order problems decriminalized designers reasoned approach" },
  { page: 50, title: "Kings Cross as Festival Terrain", chapter: 2, searchText: "festival terrain happens twice a week music festival how would one organize well-run" },
  { page: 51, title: "Young Guides in Bright T-Shirts", chapter: 2, searchText: "crime antisocial behavior designers proposed visible young guides bright T-shirts help people find way" },
  { page: 52, title: "Redesigning Kings Cross for Visitors", chapter: 2, searchText: "redesign area fulfill potential window to Australia millions visitors artworks appropriate seating" },
  { page: 53, title: "Retail Theft — Crime Prevention", chapter: 2, searchText: "retail theft shoplifting common crime costing consumers billions dollars worldwide retailers crime prevention invisible" },
  { page: 54, title: "New Retail Shelf Design", chapter: 2, searchText: "original situation proposed new retail shelf design DOC students rack easily released" },
  { page: 55, title: "YD as Experimentation Platform", chapter: 2, searchText: "Young Designers foundation platform experimentation new design practices experimental radical changes" },
  { page: 56, title: "Value of Design Inquiries", chapter: 2, searchText: "many organizations discovered value inquiries Young Designers foundation become well established" },
  { page: 57, title: "Deeper Value of Design for Organizations", chapter: 2, searchText: "concentrating pioneering organizations seeking understand deeper value design offer different organizations translating" },
  { page: 58, title: "Chapter 3: Lessons from Design — Four Questions", chapter: 3, searchText: "lessons from design four questions about design quick run-through contemporary design practice" },
  { page: 59, title: "Product Design — Technical and Marketable", chapter: 3, searchText: "product design designers torn requirement create product technically viable ergonomically sound marketable" },
  { page: 60, title: "Strategic, Deliberate, Thoughtful Approach", chapter: 3, searchText: "approach problems strategic deliberate thoughtful hard work inspirational ideas helpful never yield complete" },
  { page: 61, title: "Core Body of Knowledge About Design", chapter: 3, searchText: "core body knowledge design largely beyond contention unconventional ways stretch beyond" },
  { page: 62, title: "Reasoning in Formal Logic", chapter: 3, searchText: "penetrate core design thinking fundamentally different kinds reasoning formal logic Roozenburg Eekels" },
  { page: 63, title: "Deductive Reasoning and Prediction", chapter: 3, searchText: "solar system predict planet certain time calculations complicated reasoning deductively" },
  { page: 64, title: "Laws of Gravity and Pattern Recognition", chapter: 3, searchText: "interactions observe movement night sky laws gravity pattern relationships induction" },
  { page: 65, title: "Deduction, Induction, and Abduction", chapter: 3, searchText: "claim authority presenting work purely deductive Kuhn Latour deduction induction abduction" },
  { page: 66, title: "Normal Abduction and Problem-Solving", chapter: 3, searchText: "new scenarios normal abduction reasoning pattern conventional problem-solving tried tested patterns" },
  { page: 67, title: "Coffee Machine Example — Design Abduction", chapter: 3, searchText: "quick enough economical environmentally OK coffee machines satisfy criteria other ways design abduction" },
  { page: 68, title: "What Makes Design Hard — Problems and Paradoxes", chapter: 3, searchText: "what makes design hard problems paradoxes many issues daily lives professional practices never reach status problem" },
  { page: 69, title: "Paradoxical Problem Situations and Creativity", chapter: 3, searchText: "paradoxical problem situations inspire creative imagination famous koans Zen Buddhism capture attention" },
  { page: 70, title: "How Designers Approach a Paradox — On Framing", chapter: 3, searchText: "how designers approach paradox framing what how leads to outcome frame design abduction" },
  { page: 71, title: "Investigating Frames with Observation and Deduction", chapter: 3, searchText: "relationships desired outcomes critically investigated powers observation deduction elements frame combined" },
  { page: 72, title: "Rich Field of Opportunities", chapter: 3, searchText: "rich field opportunities people designerly bent of mind create new approach" },
  { page: 73, title: "Design Expertise — Formulating, Representing, Moving", chapter: 3, searchText: "formulating understanding identifying framing representing externalizing conversing moving primary generators" },
  { page: 74, title: "Dreyfus Model of Expertise", chapter: 3, searchText: "naive result-focused novice convention-based advanced beginner situation-based competent strategy-based expert experience-based master" },
  { page: 75, title: "Advanced Beginner — Situated Design Problems", chapter: 3, searchText: "advanced beginner recognizes design problems highly individual situated less amenable standard" },
  { page: 76, title: "Expert and Master Designers", chapter: 3, searchText: "design expertise expert master learn effectively deal open complex networked dynamic problem situations" },
  { page: 77, title: "Framing Ability and the 'Click' Moment", chapter: 3, searchText: "expert master designers framing ability crucial high-level design ideas sudden click" },
  { page: 78, title: "From Technician to Trusted Advisor", chapter: 3, searchText: "maneuver situation role technician client knows exactly needed designer carries out trusted" },
  { page: 79, title: "Client Involvement in Envisioning Future", chapter: 3, searchText: "proper design process begin creating outcome suit future context client organization closely involved envisioning" },
  { page: 80, title: "Creating Frames for Complex Problem Situations", chapter: 3, searchText: "design practice enables designers deal very open complex dynamic networked problem situations creating frames" },
  { page: 81, title: "Frames Must Be Realistic and Inspiring", chapter: 3, searchText: "frames should be capable leading realistic solutions come alive inspiring captivating draw forth mental" },
  { page: 82, title: "Frames as Episodic Motifs", chapter: 3, searchText: "engaging imagination thoughts readily move proposed direction frames episodic motifs trigger mini" },
  { page: 83, title: "Human Dimension — Needs and Values", chapter: 3, searchText: "move away problem situation toward human dimension seeking meaning realm needs values special design skill" },
  { page: 84, title: "Poetry, Novels, Films as Sources for Meaning", chapter: 3, searchText: "poetry Milne novels Robinson Blaman films Sophies Choice philosophers Buber sources building description meaning" },
  { page: 85, title: "Observing Clues and Finding Themes", chapter: 3, searchText: "systematic dealing hang around aimlessly observing clues lead themes help create" },
  { page: 86, title: "Orgacom — Social Artworks for Organizations", chapter: 3, searchText: "working method artists collective Orgacom social artworks organizations strategy begins immersing" },
  { page: 87, title: "Discourse and Professional Design Practice", chapter: 3, searchText: "articulated embodied explored developed discarded professional design practice discourse contains practices thought patterns" },
  { page: 88, title: "Common Heritage of Strategies and Knowledge", chapter: 3, searchText: "strategies particular knowledge special skills range possible solutions common heritage strategic statements" },
  { page: 89, title: "Chapter 3 Transition", chapter: 3, searchText: "" },
  { page: 90, title: "Chapter 4: The Frame Creation Model", chapter: 4, searchText: "frame creation model five problem-focused design practices coevolution developing problem situations" },
  { page: 91, title: "Research Origins of Frame Creation", chapter: 4, searchText: "design teams Cross Christiaans Dorst Valkenburg van der Lugt Smulders diversified deepened research" },
  { page: 92, title: "Nine-Step Frame Creation Process", chapter: 4, searchText: "archaeology paradox context field themes frames futures transformation integration process model" },
  { page: 93, title: "Identifying the Core Paradox", chapter: 4, searchText: "several issues intertwined problem situation keep frame creation on track identify core paradox deadlock" },
  { page: 94, title: "Mapping the Field of Players", chapter: 4, searchText: "mapping field players concentrate currency power interests values practices frames exuding influence" },
  { page: 95, title: "Frames — Common Themes in the Broader Field", chapter: 4, searchText: "in-depth analysis broader field common themes emerge different from those underlying original paradox shared" },
  { page: 96, title: "Value Proposition for All Parties", chapter: 4, searchText: "develop fledgling version value proposition parties involved frame solution ideas only as good as" },
  { page: 97, title: "Case Studies — Analysis and Creation", chapter: 4, searchText: "case studies oscillation between analysis creation central creative design practice zooming in" },
  { page: 98, title: "Sydney Opera House Podium Security", chapter: 4, searchText: "Sydney Opera House podium traditional security response increase level security block restrict access" },
  { page: 99, title: "The Security Paradox — Direct Contradiction", chapter: 4, searchText: "direct contradiction two becauses stalemate increasing level security personnel helped resolve paradox" },
  { page: 100, title: "Experiencing the Opera House — Surrounded by the Building", chapter: 4, searchText: "only place feel surrounded building admire wonderful detailing sails pattern tiles glow light" },
  { page: 101, title: "Sydneysiders Avoid the Headland", chapter: 4, searchText: "prepackaged must-see tourist attraction does not connect city Sydney local population Sydneysiders avoids headland" },
  { page: 102, title: "Creating a Sense of Place", chapter: 4, searchText: "problem situation Opera House podium approached creating sense of place podium should convey" },
  { page: 103, title: "Protecting the Sails and Infrastructure", chapter: 4, searchText: "protesters climb up seeking make morning headlines protect highest sails prime target infrastructure needed" },
  { page: 104, title: "Possible Future Designs for the Podium", chapter: 4, searchText: "possible future designs Sydney Opera House podium sketch DOC staff" },
  { page: 105, title: "Case 12: Retail in the Information Age", chapter: 4, searchText: "survival fittest retail information age department store specializing clothing Designing Out Crime center redesign" },
  { page: 106, title: "The Fitting Room Paradox", chapter: 4, searchText: "fitting rooms good hiding places become location theft measures taken reduce experience" },
  { page: 107, title: "A Larger Question for the Development Project", chapter: 4, searchText: "field yields second much larger question development project overriding influence design" },
  { page: 108, title: "The Catwalk Concept — Futures", chapter: 4, searchText: "futures preliminary physical design proposal catwalk middle store built-in cameras customer" },
  { page: 109, title: "Catwalk as Retail Feature", chapter: 4, searchText: "catwalk proposed feature retail environment sketch DOC staff catapulting middle store easier control check" },
  { page: 110, title: "Case 13: Stratums Eind — Eindhoven Nightlife", chapter: 4, searchText: "archaeology problem situation center Eindhoven Stratums Eind old narrow street cafes clubs party spot young people" },
  { page: 111, title: "Eindhoven's Rapid Expansion", chapter: 4, searchText: "media coverage makes parents deeply worried kids going out physical layout Eindhoven expanded rapidly 1950s" },
  { page: 112, title: "Learning to Manage Risk", chapter: 4, searchText: "learn manage risk own lives parents overly worried protective judging kid too naive" },
  { page: 113, title: "Suburban Lifestyle Choices", chapter: 4, searchText: "suburbs what makes difficult problem parents live suburbs chosen certain lifestyle safe" },
  { page: 114, title: "Integration — Risk, Responsibilities, Emotional Distance", chapter: 4, searchText: "integration looking city through filters dealing risk responsibilities emotional distance fruitful exercise" },
  { page: 115, title: "Two-Hour Frame Creation Sessions", chapter: 4, searchText: "two-hour frame creation sessions outcome number possibly useful frames need explored depth definitive choice" },
  { page: 116, title: "Chapter 5: Principles and Practices of Frame Creation", chapter: 5, searchText: "principles practices frame creation model chapter 4 outlines process nine steps guide" },
  { page: 117, title: "Deeper Principles of Frame Creation", chapter: 5, searchText: "deeper principles capture core approach applied processes many shapes sizes ease of use" },
  { page: 118, title: "Ten Principles — Attack Context, Suspend Judgment", chapter: 5, searchText: "attack context suspend judgment embrace complexity zoom out expand concentrate search patterns deepen themes sharpen frames" },
  { page: 119, title: "Principle 1–2: Attack Context, Suspend Judgment", chapter: 5, searchText: "attacking context allows move beyond symptoms root causes suspend judgment opening new avenues opportunities" },
  { page: 120, title: "Reducing Scope Through Assumptions", chapter: 5, searchText: "tend reduce scope problems introducing assumptions framing simple manner frame creation assumptions challenged" },
  { page: 121, title: "Universals and New Frames", chapter: 5, searchText: "possibilities sparked emergence common themes universals create new frames problem situation proposed actions" },
  { page: 122, title: "Zooming Out and Concentrating", chapter: 5, searchText: "frame creation zooming out and concentrating problem paradox context field theme frame futures transformation integration" },
  { page: 123, title: "Principle 6: Deepen Themes", chapter: 5, searchText: "deepen themes most abstract activity frame creation hardest to grasp people new approach yet crucial" },
  { page: 124, title: "Avoiding Over-Focus on One Group", chapter: 5, searchText: "over focus creating good late-night experience one particular group youngsters young males going out together" },
  { page: 125, title: "Problem Situation Map", chapter: 5, searchText: "problem situation map Duisters student TU Eindhoven project loitering teens participants strategically chosen" },
  { page: 126, title: "Principle 10: Follow Through", chapter: 5, searchText: "follow through frame creation doesnt end focused high-energy exchanges frame creation workshop much work" },
  { page: 127, title: "Cautiously Developing the Problem Situation", chapter: 5, searchText: "problem-solving approach frame creation step back cautiously find way develop problem situation fruitfully approached" },
  { page: 128, title: "Smart Work Hubs Case Study", chapter: 5, searchText: "Smart Work Hubs other countries generic work spaces rent desk bespoke solutions" },
  { page: 129, title: "Creative Precinct and Collaboration", chapter: 5, searchText: "collaborate closely delivery projects creative precinct creatives international outlook wider-ranging needs context" },
  { page: 130, title: "Attract, Monitor, Reflect, Support, Collaborate", chapter: 5, searchText: "attract monitor reflect support collaborate Smart Work Hubs development cycle collaborations emerge evaluate benefits" },
  { page: 131, title: "Physical Hub Models — Market, Bazaar, Convention", chapter: 5, searchText: "framing physical hub patterned different familiar models market bazaar convention center precinct courtyard village" },
  { page: 132, title: "Deprivation as New Normality", chapter: 5, searchText: "generation new normality government private initiatives charities responded immediate needs many projects" },
  { page: 133, title: "Identity, Aspiration, Empowerment", chapter: 5, searchText: "identity who am I reflections aspiration what does this mean what can I hope empowerment what can I do personal societal transformation" },
  { page: 134, title: "Restoring Natural Flow — Multiple Frames", chapter: 5, searchText: "many more frames ideas built around other groups population restoring natural flow streams marshes" },
  { page: 135, title: "Shame and Stigma of Loneliness", chapter: 5, searchText: "shame real taboo people do not like talk about stigma associated loneliness loser when lonely" },
  { page: 136, title: "Sensitivity and Quality of Perception", chapter: 5, searchText: "alone linked special sensitivity quality perception created moving series photos taken such moments" },
  { page: 137, title: "Guilt in Care Situations", chapter: 5, searchText: "guilt care situation caregivers often feel selfish when help themselves realization solutions should not feeling" },
  { page: 138, title: "Chapter 6: The Open, Complex, Dynamic Organization — Driving Innovation", chapter: 6, searchText: "open complex dynamic networked organization driving innovation current interest design thinking sparked trouble organizations" },
  { page: 139, title: "Audio Systems and New Technologies", chapter: 6, searchText: "periodical creation new audio systems what sometimes under pressure advent new technologies CD carrier digitized music how" },
  { page: 140, title: "Five Levels — Routine Reaction to Continuous Process", chapter: 6, searchText: "routine reaction conventional practice frame adoption frame creation projects frame creation continuous process five levels" },
  { page: 141, title: "Design Abduction Mode", chapter: 6, searchText: "conventional practice frame adoption frame creation normal abduction new what design abduction mode also require new how" },
  { page: 142, title: "Avoidance Behavior in Organizations", chapter: 6, searchText: "application new approach without renewing own discourse avoidance behavior incredibly effective practicing" },
  { page: 143, title: "Themes as Flexible Basis for Identity", chapter: 6, searchText: "themes ability create frames spring from themes flexible basis identity toward frame innovation companies government" },
  { page: 144, title: "Organizations Becoming Defensive", chapter: 6, searchText: "exactly opposite direction disastrous organizations becoming very defensive all walks life" },
  { page: 145, title: "The Promise of Being a Frame Innovator", chapter: 6, searchText: "full-blown crises profound promise becoming frame innovator existing world relating fosters less nervous problem-prone" },
  { page: 146, title: "Changing City Dynamics at Night", chapter: 6, searchText: "city council inspired realization possible change dynamics city at night positive way not just enforcement" },
  { page: 147, title: "Academic Designer and Complex Problems", chapter: 6, searchText: "academic level Dorst new academic designer able deal more complex problems traditional skills-based design paradigms" },
  { page: 148, title: "New Practice Takes Root — Seeing, Thinking, Doing", chapter: 6, searchText: "certain new practice taken root three elements seeing thinking doing implemented feedback mechanism" },
  { page: 149, title: "Chapter 6 Transition", chapter: 6, searchText: "" },
  { page: 150, title: "Chapter 7: The Three Challenges of Frame Innovation", chapter: 7, searchText: "three challenges frame innovation convinced frame creation much-needed extension repertoire problem-solving approaches" },
  { page: 151, title: "Seeing, Thinking, and Doing Differently", chapter: 7, searchText: "notion rationality doing world set ways dealing novelty innovation frame creation seeing thinking doing differently" },
  { page: 152, title: "When Frames Surface as Paths to Solution", chapter: 7, searchText: "type solution begins surface next step frames proposed paths solution disciplinary approaches" },
  { page: 153, title: "Frames Are Intrinsic — Cannot Formulate Without", chapter: 7, searchText: "first two steps concentrate problem as presented frames intrinsic cannot formulate approach problem without" },
  { page: 154, title: "Zooming Out and Concentrating (Reprise)", chapter: 7, searchText: "problem paradox context field theme frame futures transformation integration zooming out concentrating" },
  { page: 155, title: "Assumptions of Rational Thought", chapter: 7, searchText: "rational thought disembodied dispassionate practical reasoning theoretical reasoning Lakoff Johnson" },
  { page: 156, title: "Six Properties of Rational Thought", chapter: 7, searchText: "rational thought literal logical conscious disembodied dispassionate theoretical reasoning distinction" },
  { page: 157, title: "Problem Situation Fails Rationalistic Assumptions", chapter: 7, searchText: "analysis shows problem situation badly fails assumptions needed rationalistic approach yet followed problem owner felt" },
  { page: 158, title: "Improvisation Based on Experience", chapter: 7, searchText: "eternal now continuously improvise based experience habit sense pattern gut feeling drive move certain direction" },
  { page: 159, title: "Inner Logic of Frame Creation", chapter: 7, searchText: "inner logic frame creation process assumptions different stakeholders form basis own positions" },
  { page: 160, title: "Beyond the Rational High Ground", chapter: 7, searchText: "beyond rational high ground thoughtful logical approaches developed help traverse terrain requires" },
  { page: 161, title: "Isolating Creative Steps Within Rationalism", chapter: 7, searchText: "evaluation step follows clever isolation creative steps within rationalist process successful frame creation different" },
  { page: 162, title: "Brainstorming and Creative Sessions", chapter: 7, searchText: "creativity embodied techniques brainstorming creative sessions wide spread associations ideas" },
  { page: 163, title: "Sidestepping Innovation-Adverse Organizations", chapter: 7, searchText: "completion withstanding attacks innovation-adverse organization sidestepping physical nature skunk works" },
  { page: 164, title: "Success Measures and Best Practices", chapter: 7, searchText: "prevalent measure success marketing select best practices study emulate does not correspond managers" },
  { page: 165, title: "Cutting Out Risk While Achieving Innovation", chapter: 7, searchText: "creation approach cuts out risk still achieving radical innovation eliminating risk rules out hero classic sense" },
  { page: 166, title: "Entrepreneurship and Herbert Simon's Theories", chapter: 7, searchText: "adherence entrepreneuring scholars Herbert Simon theories entrepreneurial activity seen rather limiting lens" },
  { page: 167, title: "Chapter 7 Transition", chapter: 7, searchText: "" },
  { page: 168, title: "Chapter 8: The Art of Frame Innovation — Making It Happen", chapter: 8, searchText: "art frame innovation making it happen situated process requires new thinking every time never recipe set actions followed" },
  { page: 169, title: "Eindhoven Marathon Case Study", chapter: 8, searchText: "marathon held city every autumn extensive period dialogue stakeholders two-hour frame creation workshop" },
  { page: 170, title: "The Semiparadox", chapter: 8, searchText: "semiparadox arises chain reasoning first third statement not very well aligned context problem mapped" },
  { page: 171, title: "Workshop Discussion — Companies and Health", chapter: 8, searchText: "participants workshop discussed groups thoroughly discussion gradually focused companies double interest promoting healthy" },
  { page: 172, title: "Marathon as Neighborhood Event", chapter: 8, searchText: "marathon approached as if neighborhood event city Eindhoven provide frame dividing marathon circuit" },
  { page: 173, title: "Futures — Combining Several Frames", chapter: 8, searchText: "futures development design concepts action scenarios based frames combine several frames integrating needs widest" },
  { page: 174, title: "City Themes and Their Location", chapter: 8, searchText: "health community business design city life education culture leisure technology Eindhoven Marathon city themes location" },
  { page: 175, title: "Challenging Practices — Becoming Frame Innovators", chapter: 8, searchText: "frame creation methodology creates new space initiatives challenges involved transform practices become frame innovators integration" },
  { page: 176, title: "Scope Collapse and Limitations", chapter: 8, searchText: "working with quite tangential core issues little influence scope project gradually collapsed tampering" },
  { page: 177, title: "Frame Creation Projects — Curiously Strong and Solid", chapter: 8, searchText: "frame creation projects often curiously strong solid innate capacity help unlock analytical creative capabilities" },
  { page: 178, title: "Choosing the Right Themes", chapter: 8, searchText: "choosing right themes high-level experts involved guide process along practice moments" },
  { page: 179, title: "Stakeholders and the Field — Workshop Method", chapter: 8, searchText: "players field left side large piece paper steps write down what is important needs values practices" },
  { page: 180, title: "Workshop Process — Go With the Flow", chapter: 8, searchText: "stakeholders frames creates more vision most remarkable concepts go with the flow themes" },
  { page: 181, title: "External Factors and Aggressive Behavior", chapter: 8, searchText: "physical biological changes external factors evening Kings Cross trigger aggressive overly boisterous behavior" },
  { page: 182, title: "Theme Map — Identity, Risk, Leadership", chapter: 8, searchText: "weak external strong internal social individual identity formation physical learning intellectual success dynamics risk leadership testing strength" },
  { page: 183, title: "Catalysts and Conductors", chapter: 8, searchText: "catalysts conductors frame creation approach presented process model explicating principles logic" },
  { page: 184, title: "Research, Initiation, Frame Creation Cycle", chapter: 8, searchText: "research gather knowledge required tackle problem situation identify stakeholders initiation key stakeholders contacted project formed" },
  { page: 185, title: "Benefits — Integrating Research, Education, Engagement", chapter: 8, searchText: "several benefits university good way integrate research education external engagement frame creation process" },
  { page: 186, title: "Organizations as Overlapping Frames", chapter: 8, searchText: "interesting perspective organizations addition perspectives chapter 6 view organization set overlapping" },
  { page: 187, title: "DOC Method Cards", chapter: 8, searchText: "sample DOC method cards ownership responsibility process creating set cards therapeutic quality giving each team" },
  { page: 188, title: "Design and Research Tools", chapter: 8, searchText: "common design research tools designers Laurel Kumar set frame creation method cards open-ended" },
  { page: 189, title: "Transdisciplinary Process and Networks", chapter: 8, searchText: "transdisciplinary process new type network people working together communities themes frames ideas cross-pollinate travel" },
  { page: 190, title: "Case 1 Revisited: High-Speed Train — All's Well", chapter: 8, searchText: "high-speed train revisited alls well that ends well return draw lessons classic drama reporting" },
  { page: 191, title: "Practical Problems and Compromise", chapter: 8, searchText: "practical problems mostly overcome compromise splitting inconvenience tunnel not ideally placed neighbors" },
  { page: 192, title: "Organizations Must Adapt Problem-Solving", chapter: 8, searchText: "organizations increasingly faced open complex dynamic networked problem situations adapt problem-solving ability cope" },
  { page: 193, title: "Chapter 8 Transition", chapter: 8, searchText: "" },
  { page: 194, title: "Appendix 1: An Expert Designer at Work", chapter: 9, searchText: "appendix expert designer at work colleague Henri Christiaans studied individual designers design task think aloud thought patterns" },
  { page: 195, title: "Expert Designer — Newspaper Bins", chapter: 9, searchText: "thrown away main kind litter design bins compartment newspapers can be put in time 62 minutes" },
  { page: 196, title: "Expert Designer — Finding Solutions", chapter: 9, searchText: "28 percent find something important more problems too small of course time 68 minutes" },
  { page: 197, title: "Product Design — Passenger Comfort", chapter: 9, searchText: "bins easy reach passenger quite big limit passenger comfort classic problem product designers product needs to be there" },
  { page: 198, title: "Primary Generator and Coherent Story", chapter: 9, searchText: "generator guiding possible interpretation problem situation follow twists turns designer closely reads coherent story" },
  { page: 199, title: "Appendix 1 Transition", chapter: 9, searchText: "" },
  { page: 200, title: "Appendix 2: Is Design Searching or Learning?", chapter: 9, searchText: "appendix is design searching or learning first paradigm researchers studied understand design Herbert Simon early 1970s" },
  { page: 201, title: "Simon's Inner and Outer Environment", chapter: 9, searchText: "system goals outer environment minimal assumptions inner environment Simon 1969 later paper Simon 1973 addressed" },
  { page: 202, title: "Schon's Reflective Practice", chapter: 9, searchText: "underlying background theory corresponds designer view design problems personal goals Schon contrasts reflective practice" },
  { page: 203, title: "Appendix 2 Transition", chapter: 9, searchText: "" },
  { page: 204, title: "Appendix 3: More Research Is Needed", chapter: 9, searchText: "appendix more research needed development frame creation proof of concept core process model true design-based methodology organizations" },
  { page: 205, title: "Limitations of Frame Creation", chapter: 9, searchText: "learned a lot frame creation much more discover several limitations frame creation approach need addressed application" },
  { page: 206, title: "Appendix 4: Inspiration", chapter: 9, searchText: "appendix inspiration inspiring features frame creation open approach uses breadth human qualities individuals organizations" },
  { page: 207, title: "Humanity, the Higher, and the World", chapter: 9, searchText: "higher religion humanity creation culture the world Australian indigenous cultures within wholeness" },
  { page: 208, title: "Mechanistic View and Objective Study", chapter: 9, searchText: "subject objective study application reason attainment understanding truth mechanistic view world human existence overwhelming" },
  { page: 209, title: "Renku Master and Hindu Philosophy", chapter: 9, searchText: "unfathomable careful study language renku master understand crucial design skill deeper level Hindu philosophy" },
  { page: 210, title: "References (A–D)", chapter: 9, searchText: "references Argyris organizational learning Bourdieu Deming Cross Christiaans Dorst" },
  { page: 211, title: "References (D–G)", chapter: 9, searchText: "references Dickson Dansk Design van Dijk Network Society Dorst Describing Design Comparison Paradigms" },
  { page: 212, title: "References (G–I)", chapter: 9, searchText: "references Gamman Thorpe role-playing tool design against crime aid designers" },
  { page: 213, title: "References (I–L)", chapter: 9, searchText: "references IDEO Method Cards 51 Ways Inspire Design Jacobsen Encountering Everyday sociologies unnoticed" },
  { page: 214, title: "References (M–S)", chapter: 9, searchText: "references Martin Design of Business Morgan Images Organization Mulder" },
  { page: 215, title: "References (S–W)", chapter: 9, searchText: "references Smulders Get Synchronized bridging gap design volume production Stacey Griffin Shaw" },
  { page: 216, title: "References (W–Z)", chapter: 9, searchText: "references Whitbeck Ethics Engineering Practice Research Winograd Flores Understanding Computers Cognition" },
  { page: 217, title: "Index Title Page", chapter: 9, searchText: "" },
  { page: 218, title: "Index (A–D)", chapter: 9, searchText: "index abduction academic design aloneness Amsterdam Historic Museum archaeology Argyris Bang Olufsen Basho behavior Bourdieu" },
  { page: 219, title: "Index (D–I)", chapter: 9, searchText: "index design continued misunderstanding mysteriousness not irrational reasoning strategic expertise model designing practices roles Designing Out Crime" },
  { page: 220, title: "Index (I–R)", chapter: 9, searchText: "index implementation improvisation induction industrial economy innovation management integration intellectual capital intuition rationality" },
  { page: 221, title: "Index (R–Z)", chapter: 9, searchText: "index rationality reflection in action renku representation retail risk Roozenburg routine Schon Senge shame" }
];
